spring.datasource.url=jdbc:postgresql://db.wgpapdmdqgtcwgadzrje.supabase.co:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=Prc+6n7a..As,B7

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true

server.port=8080

google.recaptcha.secret=6LebRposAAAAAD9azyhXucXHM4l4CmgaY7NtlELr